### PR TITLE
Don't change attributes to properties by default.

### PR DESCRIPTION
**Pull request by JorgeBucaran**
Hi👋, the idea with this PR is to make hyperx behavior less opinionated.

Also related: #48, #49.

### CODE REVIEW

**Comment by jbucaran** [comment]
@substack Can we merge this?

**Comment by jbucaran** [comment]
@substack Can you take a look at this? 🙏

**Comment by jbucaran** [comment]
@substack Can you have a look?

**Comment by yoshuawuyts** [comment]
@jbucaran could you perhaps explain a little what the intent is here? - I'm not sure I quite understand yet why this behavior change would be needed

**Comment by jbucaran** [comment]
@yoshuawuyts Sure. It's related to https://github.com/substack/hyperx/pull/49 where a second argument, options, was introduced to opt out [attrToProp](https://github.com/feross/hyperscript-attribute-to-property).

The default behavior in hyperx is to chage props in the data argument like class to className.

This behavior is not obligatory in order to parse a view's HTML into a hyperscript-style `h` function, nor it is hyperx concern to handle this logic. We should leave this to a DOM engine to deal in any way they like.

**Comment by jbucaran** [comment]
@substack Hello, can you review this?

**Comment by jbucaran** [comment]
@substack Hi there, can you review this or provide some resolution? 👋

**Comment by jbucaran** [comment]
@substack Hi there, can you review this or provide some resolution? 👋

**Comment by jbucaran** [comment]
@substack Ping?

**Comment by jbucaran** [comment]
@substack Ping?

**Comment by jbucaran** [comment]
@substack Ping?

**Comment by jbucaran** [comment]
@substack Ping?

**Comment by jbucaran** [comment]
@substack Hi there, can you review this or provide some resolution / advice?

**Comment by jbucaran** [comment]
@substack Hi there, can you review this or provide some resolution / advice?

**Comment by Rob-pw** [comment]
I'm going in circles here, is this issue relating to attribute `class` being renamed to `className`? It's my first experience of hyperx/hyperapp and this one quirk alone is rather confusing.

**Comment by jbucaran** [comment]
@Rob-pw 

The current behavior here is to change some of the props that you pass in the `data` argument, e.g., `class` is changed to `className`. 

This is inconvenient for v/DOM authors that want to support Hyperx, like I do with HyperApp, because it forces my code to check if an element's attribute is _`className`_ and rename it to _`class`_ for no good reason.

**Comment by Rob-pw** [comment]
Is there a good solution for this bar running off with jsx? At the moment it seems broken, attribute `class` gets changed to `classname` (lowercase, and is left like that on the element, meaning no styles are applied). I've tried using `class` , `className`, `classname`, in my markup but all of these end up as `classname` on the element. I was wondering why none of the examples use a class attribute.

```html
<button class="mdl-button">
  Button
</button>
```

**Comment by Rob-pw** [comment]
Ah yes, the solution seems to be in the PR that I am commenting on. Thanks @jbucaran. If this could be merged into master, that'd be ace.

**Comment by jbucaran** [comment]
@substack Is this going to get merged?

**Comment by JorgeBucaran** [comment]
@yoshuawuyts Could you have a look?

**Comment by yoshuawuyts** [comment]
Haha, hey! — sorry for not getting back to you sooner. I think the tradeoff here is that it'll probably break what we're doing with Choo and other modules, which simply means spending some time to make sure everything still works.

I'm a bit constrained on time at the moment, hence why I've kinda just left this; and I guess nobody else has picked this up either.

I'll be in Tokyo in a few weeks; if you want we can perhaps hang out sometime, merge this, and fix the fallout together C: It's all just chores, so not being alone in doing this would be neat haha. Cheers!

**Comment by JorgeBucaran** [comment]
@yoshuawuyts That would great. Oh, really, are you coming to nodefest perhaps?

**Comment by yoshuawuyts** [comment]
@JorgeBucaran December 1st; so right the week after :D

**Pull request closed without merging**
